name: "Continuous Integration"

on:
  push:
    branches:
      - master
  pull_request:

env:
  fail-fast: true

jobs:
  tests:
    name: "Symfony1 Tests"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
        memcached-version:
          - "1.6"

    services:
      memcached:
        image: "memcached:${{ matrix.memcached-version }}"
        ports:
          - 11211:11211

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "json,memcached,apcu"
          ini-values: date.timezone=UTC,memory_limit=-1
          tools: pecl

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run Check configuration
        run: php data/bin/check_configuration.php

      - name: Run Tests
        run: php vendor/bin/phpunit
        env:
          MEMCACHED_HOST: 'localhost:11211'